AWSTemplateFormatVersion: 2010-09-09
Description: AWS Cloud WAN centralized east-west single-hop (Global & core network)

Resources:
  GlobalNetwork:
    Type: AWS::NetworkManager::GlobalNetwork
    Properties:
      Description: Global Network - East-West (single-hop)
      Tags:
        - Key: Name
          Value: global-network-east-west-singlehop

  CoreNetwork:
    Type: AWS::NetworkManager::CoreNetwork
    Properties:
      Description: Core Network - East-West (single-hop)
      GlobalNetworkId: !Ref GlobalNetwork
      Tags:
        - Key: Name
          Value: core-network-east-west-singlehop
      PolicyDocument:
        version: "2021.12"
        core-network-configuration:
          vpn-ecmp-support: false
          asn-ranges:
            - 64520-65525
          edge-locations:
            - location: eu-west-1
            - location: us-east-1
            - location: us-west-2
        segments:
          - name: production
            require-attachment-acceptance: false
            isolate-attachments: true
          - name: development
            require-attachment-acceptance: false
        network-function-groups:
          - name: inspectionVpcs
            require-attachment-acceptance: false
        attachment-policies:
          - rule-number: 100
            conditions:
              - type: tag-value
                operator: equals
                key: inspection
                value: true
            action:
              add-to-network-function-group: inspectionVpcs
          - rule-number: 200
            conditions:
              - type: tag-exists
                key: domain
            action:
              association-method: tag
              tag-value-of-key: domain
        segment-actions:
          - action: send-via
            segment: production
            mode: single-hop
            via:
              network-function-groups:
                - inspectionVpcs
              with-edge-overrides:
                - edge-sets:
                    - - eu-west-1
                      - us-east-1
                    - - eu-west-1
                      - us-west-2
                  use-edge-location: eu-west-1
                - edge-sets:
                    - - us-west-2
                      - us-east-1
                  use-edge-location: us-east-1

Outputs:
  CoreNetworkId:
    Description: Core Network ID.
    Value: !GetAtt CoreNetwork.CoreNetworkId
  CoreNetworkArn:
    Description: Core Network ARN.
    Value: !GetAtt CoreNetwork.CoreNetworkArn