AWSTemplateFormatVersion: 2010-09-09
Description: AWS Cloud WAN Filtering - IPv4 & IPv6 only segments (Global & Core network)

Resources:
  GlobalNetwork:
    Type: AWS::NetworkManager::GlobalNetwork
    Properties:
      Description: Global Network - IPv4-IPv6-only segments
      Tags:
        - Key: Name
          Value: global-network-ipv4-ipv6-only-segments

  CoreNetwork:
    Type: AWS::NetworkManager::CoreNetwork
    Properties:
      Description: Core Network - IPv4-IPv6-only segments
      GlobalNetworkId: !Ref GlobalNetwork
      Tags:
        - Key: Name
          Value: core-network-ipv4-ipv6-only-segments
      PolicyDocument:
        version: '2025.11'
        core-network-configuration:
          vpn-ecmp-support: true
          dns-support: true
          security-group-referencing-support: true
          asn-ranges:
            - 65000-65003
          edge-locations:
            - location: us-east-1
              asn: 65000
            - location: eu-west-1
              asn: 65001
        segments:
          - name: production
            require-attachment-acceptance: false
          - name: development
            require-attachment-acceptance: false
          - name: ipv4only
          - name: ipv6only
        attachment-policies:
          - rule-number: 100
            condition-logic: and
            conditions:
              - type: attachment-type
                operator: equals
                value: vpc
              - type: tag-exists
                key: domain
            action:
              association-method: tag
              tag-value-of-key: domain
        segment-actions:
          - action: share
            mode: attachment-route
            segment: ipv4only
            share-with:
              - production
            routing-policy-names:
              - filterIpv6
          - action: share
            mode: attachment-route
            segment: ipv4only
            share-with:
              - development
            routing-policy-names:
              - filterIpv6
          - action: share
            mode: attachment-route
            segment: ipv6only
            share-with:
              - production
            routing-policy-names:
              - filterIpv4
          - action: share
            mode: attachment-route
            segment: ipv6only
            share-with:
              - development
            routing-policy-names:
              - filterIpv4
        routing-policies:
          - routing-policy-name: filterIpv4
            routing-policy-description: Filtering all IPv4 ranges
            routing-policy-direction: inbound
            routing-policy-number: 100
            routing-policy-rules:
              - rule-number: 100
                rule-definition:
                  match-conditions:
                    - type: prefix-in-cidr
                      value: 0.0.0.0/0
                  condition-logic: or
                  action:
                    type: drop
          - routing-policy-name: filterIpv6
            routing-policy-description: Filtering all IPv6 ranges
            routing-policy-direction: inbound
            routing-policy-number: 200
            routing-policy-rules:
              - rule-number: 100
                rule-definition:
                  match-conditions:
                    - type: prefix-in-cidr
                      value: ::/0
                  condition-logic: or
                  action:
                    type: drop

Outputs:
  CoreNetworkId:
    Description: Core Network ID.
    Value: !GetAtt CoreNetwork.CoreNetworkId
  CoreNetworkArn:
    Description: Core Network ARN.
    Value: !GetAtt CoreNetwork.CoreNetworkArn
