AWSTemplateFormatVersion: 2010-09-09
Description: AWS Cloud WAN Filtering Secondary CIDRs (Global & Core network)

Resources:
  GlobalNetwork:
    Type: AWS::NetworkManager::GlobalNetwork
    Properties:
      Description: Global Network - Filtering Secondary CIDRs
      Tags:
        - Key: Name
          Value: global-network-filtering-secondary-cidrs

  CoreNetwork:
    Type: AWS::NetworkManager::CoreNetwork
    Properties:
      Description: Core Network - Filtering Secondary CIDRs
      GlobalNetworkId: !Ref GlobalNetwork
      Tags:
        - Key: Name
          Value: core-network-filtering-secondary-cidrs
      PolicyDocument:
        version: '2025.11'
        core-network-configuration:
          vpn-ecmp-support: true
          dns-support: true
          security-group-referencing-support: true
          asn-ranges:
            - 65000-65003
          edge-locations:
            - location: us-east-1
              asn: 65000
            - location: eu-west-1
              asn: 65001
        segments:
          - name: production
            require-attachment-acceptance: false
          - name: development
            require-attachment-acceptance: false
        attachment-policies:
          - rule-number: 100
            condition-logic: and
            conditions:
              - type: attachment-type
                operator: equals
                value: vpc
              - type: tag-exists
                key: domain
            action:
              association-method: tag
              tag-value-of-key: domain
        attachment-routing-policy-rules:
          - rule-number: 100
            conditions:
              - type: routing-policy-label
                value: vpcAttachments
            action:
              associate-routing-policies:
                - secondaryCidrFiltering
        routing-policies:
          - routing-policy-name: secondaryCidrFiltering
            routing-policy-description: Attachment IPv4 secondary CIDR block filtering
            routing-policy-direction: inbound
            routing-policy-number: 100
            routing-policy-rules:
              - rule-number: 100
                rule-definition:
                  match-conditions:
                    - type: prefix-equals
                      value: 10.100.0.0/16
                  condition-logic: or
                  action:
                    type: drop

Outputs:
  CoreNetworkId:
    Description: Core Network ID.
    Value: !GetAtt CoreNetwork.CoreNetworkId
  CoreNetworkArn:
    Description: Core Network ARN.
    Value: !GetAtt CoreNetwork.CoreNetworkArn
