AWSTemplateFormatVersion: 2010-09-09
Description: AWS Cloud WAN Filtering - Influencing DXGW hybrid path (Global & Core network)

Resources:
  GlobalNetwork:
    Type: AWS::NetworkManager::GlobalNetwork
    Properties:
      Description: Global Network - Influencing DXGW hybrid path
      Tags:
        - Key: Name
          Value: global-network-influencing-dxgw-hybrid-path

  CoreNetwork:
    Type: AWS::NetworkManager::CoreNetwork
    Properties:
      Description: Core Network - Influencing DXGW hybrid path
      GlobalNetworkId: !Ref GlobalNetwork
      Tags:
        - Key: Name
          Value: core-network-influencing-dxgw-hybrid-path
      PolicyDocument:
        version: '2025.11'
        core-network-configuration:
          vpn-ecmp-support: true
          dns-support: true
          security-group-referencing-support: true
          asn-ranges:
            - 65000-65003
          edge-locations:
            - location: us-east-1
              asn: 65000
            - location: eu-west-1
              asn: 65001
        segments:
          - name: europevpcs
            require-attachment-acceptance: false
          - name: usvpcs
            require-attachment-acceptance: false
          - name: hybrid
            require-attachment-acceptance: false
        attachment-policies:
          - rule-number: 100
            condition-logic: and
            conditions:
              - type: attachment-type
                operator: equals
                value: vpc
              - type: region
                operator: equals
                value: eu-west-1
            action:
              association-method: constant
              segment: europevpcs
          - rule-number: 200
            condition-logic: and
            conditions:
              - type: attachment-type
                operator: equals
                value: vpc
              - type: region
                operator: equals
                value: us-east-1
            action:
              association-method: constant
              segment: usvpcs
          - rule-number: 300
            condition-logic: or
            conditions:
              - type: attachment-type
                operator: equals
                value: direct-connect-gateway
            action:
              association-method: constant
              segment: hybrid
        segment-actions:
          - action: share
            mode: attachment-route
            segment: hybrid
            share-with:
              - europevpcs
            # routing-policy-names:
            #   - addASPathUS
          - action: share
            mode: attachment-route
            segment: hybrid
            share-with:
              - usvpcs
            # routing-policy-names:
            #   - addASPathEurope
          - action: share
            mode: attachment-route
            segment: europevpcs
            share-with:
              - usvpcs
        # routing-policies:
        #   - routing-policy-name: addASPathEurope
        #     routing-policy-description: Adding extra ASNs for Europe's DXGW
        #     routing-policy-direction: outbound
        #     routing-policy-number: 100
        #     routing-policy-rules:
        #       - rule-number: 100
        #         rule-definition:
        #           match-conditions:
        #             - type: asn-in-as-path
        #               value: 64512
        #           condition-logic: or
        #           action:
        #             type: prepend-asn-list
        #             value:
        #               - 65500
        #               - 65501
        #   - routing-policy-name: addASPathUS
        #     routing-policy-description: Adding extra ASNs for US' DXGW
        #     routing-policy-direction: outbound
        #     routing-policy-number: 200
        #     routing-policy-rules:
        #       - rule-number: 100
        #         rule-definition:
        #           match-conditions:
        #             - type: asn-in-as-path
        #               value: 64513
        #           condition-logic: or
        #           action:
        #             type: prepend-asn-list
        #             value:
        #               - 65500
        #               - 65501

Outputs:
  CoreNetworkId:
    Description: Core Network ID.
    Value: !GetAtt CoreNetwork.CoreNetworkId
  CoreNetworkArn:
    Description: Core Network ARN.
    Value: !GetAtt CoreNetwork.CoreNetworkArn
