AWSTemplateFormatVersion: 2010-09-09
Description: AWS Cloud WAN Summarization (Global & Core network)

Resources:
  GlobalNetwork:
    Type: AWS::NetworkManager::GlobalNetwork
    Properties:
      Description: Global Network - Summarization
      Tags:
        - Key: Name
          Value: global-network-summarization

  CoreNetwork:
    Type: AWS::NetworkManager::CoreNetwork
    Properties:
      Description: Core Network - Summarization
      GlobalNetworkId: !Ref GlobalNetwork
      Tags:
        - Key: Name
          Value: core-network-summarization
      PolicyDocument:
        version: '2025.11'
        core-network-configuration:
          vpn-ecmp-support: true
          dns-support: true
          security-group-referencing-support: true
          asn-ranges:
            - 65000-65003
          edge-locations:
            - location: us-east-1
              asn: 65000
            - location: eu-west-1
              asn: 65001
        segments:
          - name: production
            require-attachment-acceptance: false
          - name: development
            require-attachment-acceptance: false
          - name: hybrid
            require-attachment-acceptance: false
        attachment-policies:
          - rule-number: 100
            condition-logic: and
            conditions:
              - type: attachment-type
                operator: equals
                value: vpc
              - type: tag-exists
                key: domain
            action:
              association-method: tag
              tag-value-of-key: domain
          - rule-number: 200
            condition-logic: or
            conditions:
              - type: attachment-type
                operator: equals
                value: site-to-site-vpn
              - type: attachment-type
                operator: equals
                value: connect
              - type: attachment-type
                operator: equals
                value: direct-connect-gateway
            action:
              association-method: constant
              segment: hybrid
        segment-actions:
          - action: share
            mode: attachment-route
            segment: hybrid
            share-with:
              - production
              - development
        attachment-routing-policy-rules:
          - rule-number: 100
            edge-locations:
              - us-east-1
              - eu-west-1
            conditions:
              - type: routing-policy-label
                value: hybridAttachment
            action:
              associate-routing-policies:
                - summarizeIpv4Routes
        routing-policies:
          - routing-policy-name: summarizeIpv4Routes
            routing-policy-description: Summarize IPv4 CIDR blocks
            routing-policy-direction: outbound
            routing-policy-number: 100
            routing-policy-rules:
              - rule-number: 100
                rule-definition:
                  match-conditions:
                    - type: prefix-in-prefix-list
                      value: ipv4routes
                  condition-logic: or
                  action:
                    type: summarize
                    value: 10.0.0.0/8

Outputs:
  CoreNetworkId:
    Description: Core Network ID.
    Value: !GetAtt CoreNetwork.CoreNetworkId
  CoreNetworkArn:
    Description: Core Network ARN.
    Value: !GetAtt CoreNetwork.CoreNetworkArn
