AWSTemplateFormatVersion: 2010-09-09
Description: AWS Cloud WAN Summarization (Prefix list)
Transform: 'AWS::LanguageExtensions'

Parameters:
  CoreNetworkId:
    Type: String

Resources:
    PrefixList:
      Type: AWS::EC2::PrefixList
      Properties:
        AddressFamily: IPv4
        Entries: 
          - Cidr: 10.10.0.0/24
            Description: prod-us-east-1
          - Cidr: 10.0.0.0/24
            Description: prod-eu-west-1
          - Cidr: 10.10.1.0/24
            Description: dev-us-east-1
          - Cidr: 10.0.1.0/24
            Description: dev-eu-west-1
        MaxEntries: 4
        PrefixListName: !Join
          - '-'
          - - prefix-list
            - !Ref AWS::StackName
    
    PrefixListAssociation:
      Type: AWS::NetworkManager::CoreNetworkPrefixListAssociation
      Properties:
        CoreNetworkId: !Ref CoreNetworkId
        PrefixListAlias: ipv4routes
        PrefixListArn: !GetAtt PrefixList.Arn
