AWSTemplateFormatVersion: 2010-09-09
Description: AWS Cloud WAN Inspection After Filtering (Global & Core network)

Resources:
  GlobalNetwork:
    Type: AWS::NetworkManager::GlobalNetwork
    Properties:
      Description: Global Network - Inspection After Filtering
      Tags:
        - Key: Name
          Value: global-network-inspection-after-filtering

  CoreNetwork:
    Type: AWS::NetworkManager::CoreNetwork
    Properties:
      Description: Core Network - Inspection After Filtering
      GlobalNetworkId: !Ref GlobalNetwork
      Tags:
        - Key: Name
          Value: core-network-inspection-after-filtering
      PolicyDocument:
        version: '2025.11'
        core-network-configuration:
          vpn-ecmp-support: true
          dns-support: true
          security-group-referencing-support: true
          asn-ranges:
            - 65000-65003
          edge-locations:
            - location: us-east-1
              asn: 65000
            - location: eu-west-1
              asn: 65001
        segments:
          - name: production
            require-attachment-acceptance: false
          - name: development
            require-attachment-acceptance: false
        network-function-groups:
          - name: inspectionVpcs
            require-attachment-acceptance: false
        segment-actions:
          - action: send-via
            segment: production
            mode: dual-hop
            when-sent-to:
              segments:
                - development
            via:
              network-function-groups:
                - inspectionVpcs
        attachment-policies:
          - rule-number: 100
            condition-logic: and
            conditions:
              - type: attachment-type
                operator: equals
                value: vpc
              - type: tag-exists
                key: domain
            action:
              association-method: tag
              tag-value-of-key: domain
          - rule-number: 200
            condition-logic: or
            conditions:
              - type: tag-value
                operator: equals
                key: inspection
                value: true
            action:
              add-to-network-function-group: inspectionVpcs
        attachment-routing-policy-rules:
          - rule-number: 100
            conditions:
              - type: routing-policy-label
                value: vpcAttachments
            action:
              associate-routing-policies:
                - allowCidrRange
        routing-policies:
          - routing-policy-name: allowCidrRange
            routing-policy-description: Allowing 10.0.0.0/8 CIDR range
            routing-policy-direction: inbound
            routing-policy-number: 100
            routing-policy-rules:
              - rule-number: 100
                rule-definition:
                  match-conditions:
                    - type: prefix-in-cidr
                      value: 10.0.0.0/8
                  condition-logic: or
                  action:
                    type: allow
              - rule-number: 200
                rule-definition:
                  match-conditions:
                    - type: prefix-in-cidr
                      value: 0.0.0.0/0
                  condition-logic: or
                  action:
                    type: drop

Outputs:
  CoreNetworkId:
    Description: Core Network ID.
    Value: !GetAtt CoreNetwork.CoreNetworkId
  CoreNetworkArn:
    Description: Core Network ARN.
    Value: !GetAtt CoreNetwork.CoreNetworkArn
