name: CI - Code Quality & Documentation

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ~1.3

    - name: Install terraform-docs
      run: |
        curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.17.0/terraform-docs-v0.17.0-$(uname)-amd64.tar.gz
        tar -xzf terraform-docs.tar.gz
        chmod +x terraform-docs
        sudo mv terraform-docs /usr/local/bin/terraform-docs

    - name: Install tflint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Check for direct README.md changes in terraform folders
      run: |
        # Get list of changed files
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
        else
          CHANGED_FILES=$(git diff --name-only HEAD~1)
        fi

        # Check for README.md changes in terraform subdirectories
        README_CHANGES=$(echo "$CHANGED_FILES" | grep -E "patterns/.*/terraform/README\.md$" || true)

        # Check if terraform-docs config or .header.md files were also changed
        TFDOCS_CONFIG_CHANGED=$(echo "$CHANGED_FILES" | grep -E "\.terraform-docs\.ya?ml$" || true)
        HEADER_CHANGES=$(echo "$CHANGED_FILES" | grep -E "patterns/.*/terraform/\.header\.md$" || true)

        if [ ! -z "$README_CHANGES" ]; then
          if [ ! -z "$TFDOCS_CONFIG_CHANGED" ] || [ ! -z "$HEADER_CHANGES" ]; then
            echo "✅ README.md changes detected, but terraform-docs config or .header.md files were also changed."
            echo "📝 This suggests README.md files were regenerated properly."
            echo "Changed README.md files:"
            echo "$README_CHANGES"
            if [ ! -z "$TFDOCS_CONFIG_CHANGED" ]; then
              echo "Changed terraform-docs config: $TFDOCS_CONFIG_CHANGED"
            fi
            if [ ! -z "$HEADER_CHANGES" ]; then
              echo "Changed .header.md files: $HEADER_CHANGES"
            fi
          else
            echo "❌ ERROR: Direct changes to README.md files in terraform folders are not allowed!"
            echo "📝 Changed README.md files:"
            echo "$README_CHANGES"
            echo ""
            echo "✅ Instead, make changes to the corresponding .header.md files:"
            for readme in $README_CHANGES; do
              header_file=$(dirname "$readme")/.header.md
              echo "  - $readme → $header_file"
            done
            echo ""
            echo "💡 README.md files are auto-generated by terraform-docs from:"
            echo "   - .header.md (for custom content)"
            echo "   - *.tf files (for variables, outputs, resources)"
            exit 1
          fi
        fi

    - name: Run terraform-docs and terraform-fmt (auto-fixable)
      id: docs-fmt
      continue-on-error: true
      run: |
        # Run only terraform_docs and terraform_fmt
        pre-commit run terraform_docs --all-files || echo "terraform_docs_failed=true" >> $GITHUB_OUTPUT
        pre-commit run terraform_fmt --all-files || echo "terraform_fmt_failed=true" >> $GITHUB_OUTPUT

    - name: Auto-commit documentation and formatting fixes
      if: steps.docs-fmt.outputs.terraform_docs_failed == 'true' || steps.docs-fmt.outputs.terraform_fmt_failed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Add all files except workflow files
        git add -A
        git reset -- .github/workflows/

        # Check if there are changes to commit
        if ! git diff --cached --quiet; then
          git commit -m "Auto-fix: Update terraform documentation and formatting

          - terraform-docs: Update README.md files with latest variable/output documentation
          - terraform fmt: Format .tf files according to Terraform standards

          [skip ci]"
          git push
          echo "✅ Auto-committed documentation and formatting fixes"
        else
          echo "ℹ️ No changes to commit after terraform-docs and terraform-fmt"
        fi

    - name: Run validation and linting (manual fix required)
      run: |
        echo "🔍 Running terraform validation and linting (these require manual fixes if they fail)..."

        # These will fail the CI if they find issues
        pre-commit run terraform_validate --all-files
        pre-commit run terraform_tflint --all-files

    - name: Run other checks (auto-fixable)
      id: other-checks
      continue-on-error: true
      run: |
        echo "🔍 Running other code quality checks..."
        pre-commit run check-merge-conflict --all-files || echo "check_merge_conflict_failed=true" >> $GITHUB_OUTPUT
        pre-commit run end-of-file-fixer --all-files || echo "end_of_file_fixer_failed=true" >> $GITHUB_OUTPUT
        pre-commit run trailing-whitespace --all-files || echo "trailing_whitespace_failed=true" >> $GITHUB_OUTPUT
        pre-commit run check-yaml --all-files || echo "check_yaml_failed=true" >> $GITHUB_OUTPUT
        pre-commit run check-json --all-files || echo "check_json_failed=true" >> $GITHUB_OUTPUT

    - name: Auto-commit code quality fixes
      if: steps.other-checks.outputs.end_of_file_fixer_failed == 'true' || steps.other-checks.outputs.trailing_whitespace_failed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Add all files except workflow files
        git add -A
        git reset -- .github/workflows/

        # Check if there are changes to commit
        if ! git diff --cached --quiet; then
          git commit -m "Auto-fix: Code quality improvements

          - end-of-file-fixer: Ensure files end with newline
          - trailing-whitespace: Remove trailing whitespace

          [skip ci]"
          git push
          echo "✅ Auto-committed code quality fixes"
        else
          echo "ℹ️ No changes to commit after code quality checks"
        fi

    - name: Run non-fixable checks
      run: |
        echo "🔍 Running non-fixable code quality checks..."
        if [ "${{ steps.other-checks.outputs.check_merge_conflict_failed }}" == "true" ]; then
          echo "❌ Merge conflict markers found - manual fix required"
          pre-commit run check-merge-conflict --all-files
        fi
        if [ "${{ steps.other-checks.outputs.check_yaml_failed }}" == "true" ]; then
          echo "❌ YAML syntax errors found - manual fix required"
          pre-commit run check-yaml --all-files
        fi
        if [ "${{ steps.other-checks.outputs.check_json_failed }}" == "true" ]; then
          echo "❌ JSON syntax errors found - manual fix required"
          pre-commit run check-json --all-files
        fi
